[workspace]
resolver = "2"

[workspace.metadata.cloudflare]
project_name = "spottle"
custom_domain = "spottle.shibeprime.com"
build_command = "npm run build"
deploy_command = "npm run deploy"
output_dir = "dist"
